apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-backend.fullname" . }}
  labels:
    {{- include "app-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.NodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app-backend.selectorLabels" . | nindent 4 }}
